### PR TITLE
Update Fgenesh.md user guide

### PR DESCRIPTION
**Pull request by AnnaSyme**
Updated caption for Fig 1 (was incorrect). 
Updated information about inputs needed for running workflow. The step numbers, tool interface view and some of the required inputs have changed since the workflow was last updated, so the images are now incorrect, so deleted these for now.

### CODE REVIEW

**Review by supernord — APPROVED** [review]

**Comment by AnnaSyme** [comment]
thanks @supernord  I've merged this - should it show up on the page or is there another step?

**Comment by supernord** [comment]
@AnnaSyme - changes need to be merged with the `release` branch, and then the changes will be deployed

**Comment by AnnaSyme** [comment]
@supernord is that done periodically or should I do it on merging in general?

**Comment by supernord** [comment]
@AnnaSyme - this happens only as needed
for these changes I would suggest creating a PR and merging right away

**Comment by AnnaSyme** [comment]
@supernord ok - so normally would I still merge the PR with the main branch, and then do a second PR to the release branch if wanting it to display straight away?

**Pull request merged**
